import { TestBed, fakeAsync } from '@angular/core/testing';
import { FormField } from '@angular/forms/signals';
import { By } from '@angular/platform-browser';
import { FormsSignalLabComponent } from './forms-signal-lab.component';
import { LocalAvailabilityService } from './local-availability.service';
import { clickLab, labButton, labElement, labInput, renderLab, submitLab, typeLab } from './forms-lab.spec-helpers';

describe('FormsSignalLabComponent', () => {
  it('commits a buffered reserved title on Enter before checking pending validity', fakeAsync(() => {
    const fixture = TestBed.createComponent(FormsSignalLabComponent);
    renderLab(fixture);
    clickLab(fixture, 'Fill sample');
    const availability = fixture.debugElement.injector.get(LocalAvailabilityService);
    availability.resolve(availability.requests()[0]?.id ?? -1); renderLab(fixture);
    expect(labButton(fixture, 'Save local draft').disabled).toBeFalse();
    typeLab(fixture, '[data-title]', 'reserved', false);
    // A native Enter submission can arrive without a blur or clicking the button.
    submitLab(fixture);
    expect(availability.requests().map(request => request.title)).toEqual(['reserved']);
    expect(labElement(fixture).textContent).toContain('Validation pending: true');
    expect(labElement(fixture).textContent).toContain('Save stage: idle');
    expect(labButton(fixture, 'Complete success').disabled).toBeTrue();
    availability.resolve(availability.requests()[0]?.id ?? -1); renderLab(fixture);
    expect(labElement(fixture).textContent).toContain('This name is reserved');
    submitLab(fixture);
    expect(labElement(fixture).textContent).toContain('Save stage: idle');
    fixture.destroy();
  }));

  it('restarts same/different sample checks, clears native buffers and cancels checks on reset', fakeAsync(() => {
    const fixture = TestBed.createComponent(FormsSignalLabComponent);
    renderLab(fixture);
    const availability = fixture.debugElement.injector.get(LocalAvailabilityService);
    clickLab(fixture, 'Fill sample');
    const sameId = availability.requests()[0]?.id ?? -1;
    typeLab(fixture, '[data-title]', 'Uncommitted', false);
    clickLab(fixture, 'Fill sample');
    expect(availability.resolve(sameId)).toBeFalse();
    expect(availability.requests().length).toBe(1);
    expect(labInput(fixture, '[data-title]').value).toBe('Practice notebook');
    expect(labElement(fixture).textContent).toContain('Buffered title: Practice notebook');
    expect(labElement(fixture).textContent).toContain('Dirty: true');
    const failedId = availability.requests()[0]?.id ?? -1;
    expect(availability.fail(failedId)).toBeTrue(); renderLab(fixture);
    clickLab(fixture, 'Fill sample');
    expect(availability.requests().length).toBe(1);
    expect(availability.requests()[0]?.id).not.toBe(failedId);
    expect(labButton(fixture, 'Save local draft').disabled).toBeTrue();
    typeLab(fixture, '[data-title]', 'Different');
    const differentId = availability.requests()[0]?.id ?? -1;
    clickLab(fixture, 'Fill sample');
    expect(availability.resolve(differentId)).toBeFalse();
    expect(availability.requests().map(request => request.title)).toEqual(['Practice notebook']);
    const resetId = availability.requests()[0]?.id ?? -1;
    typeLab(fixture, '[data-title]', 'Another buffer', false);
    clickLab(fixture, 'Reset draft');
    expect(availability.resolve(resetId)).toBeFalse();
    expect(availability.requests()).toEqual([]);
    expect(labInput(fixture, '[data-title]').value).toBe('');
    expect(fixture.componentInstance.canLeave()).toBeTrue();
    fixture.destroy();
  }));

  it('uses the real disabled Signal field state throughout the awaited save and unchanged retry', fakeAsync(() => {
    const fixture = TestBed.createComponent(FormsSignalLabComponent);
    renderLab(fixture);
    clickLab(fixture, 'Fill sample');
    const availability = fixture.debugElement.injector.get(LocalAvailabilityService);
    availability.resolve(availability.requests()[0]?.id ?? -1); renderLab(fixture);
    const title = fixture.debugElement.query(By.css('[data-title]')).injector.get(FormField);
    submitLab(fixture);
    expect(title.state().disabled()).toBeTrue();
    expect(labElement(fixture).querySelector('[data-signal-root-state]')?.textContent).toContain('Root disabled: true · Submitting: true');
    expect(labElement(fixture).querySelector('form')?.getAttribute('aria-busy')).toBe('true');
    expect(labInput(fixture, '[data-title]').disabled).toBeTrue();
    clickLab(fixture, 'Fail response');
    expect(title.state().disabled()).toBeFalse();
    expect(labElement(fixture).querySelector('[data-signal-root-state]')?.textContent).toContain('Root disabled: false · Submitting: false');
    expect(title.state().pending()).toBeTrue();
    expect(availability.requests().map(request => request.title)).toEqual(['Practice notebook']);
    expect(labButton(fixture, 'Save local draft').disabled).toBeTrue();
    availability.resolve(availability.requests()[0]?.id ?? -1); renderLab(fixture);
    submitLab(fixture);
    expect(title.state().disabled()).toBeTrue();
    expect(labElement(fixture).querySelector('[data-signal-root-state]')?.textContent).toContain('Root disabled: true · Submitting: true');
    expect(labElement(fixture).textContent).toContain('Save stage: saving');
    fixture.destroy();
  }));

  it('focuses a group-only duplicate note error before an invalid annotation', fakeAsync(() => {
    const fixture = TestBed.createComponent(FormsSignalLabComponent);
    renderLab(fixture);
    clickLab(fixture, 'Fill sample');
    const availability = fixture.debugElement.injector.get(LocalAvailabilityService);
    availability.resolve(availability.requests()[0]?.id ?? -1); renderLab(fixture);
    clickLab(fixture, 'Add note'); clickLab(fixture, 'Add note');
    typeLab(fixture, '.note:nth-of-type(1) input', 'Same');
    typeLab(fixture, '.note:nth-of-type(2) input', ' same ');
    clickLab(fixture, 'Toggle optional label');
    clickLab(fixture, 'Review errors');
    expect(labElement(fixture).textContent).toContain('Use distinct note text');
    expect(document.activeElement).toBe(labInput(fixture, '.note input'));
    expect(labInput(fixture, 'input[aria-describedby=signal-annotations-error]').getAttribute('aria-invalid')).toBe('true');
    fixture.destroy();
  }));

  it('renders a safe fallback for Angular native message-less parse errors', fakeAsync(() => {
    const fixture = TestBed.createComponent(FormsSignalLabComponent);
    renderLab(fixture);
    const price = labInput(fixture, '[aria-describedby=signal-price-error]');
    spyOnProperty(price.validity, 'badInput', 'get').and.returnValue(true);
    price.dispatchEvent(new Event('input', { bubbles: true }));
    price.dispatchEvent(new Event('blur')); renderLab(fixture);
    const field = fixture.debugElement.query(By.css('[aria-describedby=signal-price-error]')).injector.get(FormField);
    expect(field.state().errors().some(issue => issue.kind === 'parse' && issue.message === undefined)).toBeTrue();
    expect(labElement(fixture).querySelector('#signal-price-error')?.textContent).toContain('Enter a value in the expected format.');
    fixture.destroy();
  }));

  it('blocks invalid/pending/duplicate saves, retains failed drafts and clears on success', fakeAsync(() => {
    const fixture = TestBed.createComponent(FormsSignalLabComponent);
    renderLab(fixture);
    const availability = fixture.debugElement.injector.get(LocalAvailabilityService);
    expect(fixture.componentInstance.canLeave()).toBeTrue();
    submitLab(fixture);
    expect(labElement(fixture).textContent).toContain('Save stage: idle');
    expect(labElement(fixture).textContent).toContain('Enter a non-blank title');
    clickLab(fixture, 'Fill sample');
    expect(availability.requests().length).toBe(1);
    submitLab(fixture);
    expect(labButton(fixture, 'Complete success').disabled).toBeTrue();
    const requestId = availability.requests()[0]?.id ?? -1;
    clickLab(fixture, `Resolve availability ${requestId}`);
    submitLab(fixture);
    expect(labElement(fixture).textContent).toContain('Save stage: saving');
    expect(fixture.componentInstance.canLeave()).toBeFalse();
    submitLab(fixture);
    expect(labInput(fixture, 'app-signal-stock-control input').disabled).toBeTrue();
    clickLab(fixture, 'Fail response');
    expect(labInput(fixture, '[data-title]').value).toBe('Practice notebook');
    expect(labElement(fixture).textContent).toContain('Draft preserved');
    for (const request of availability.requests()) availability.resolve(request.id);
    renderLab(fixture);
    submitLab(fixture);
    clickLab(fixture, 'Complete success');
    expect(labInput(fixture, '[data-title]').value).toBe('');
    expect(labElement(fixture).textContent).toContain('Draft cleared');
    expect(fixture.componentInstance.canLeave()).toBeTrue();
    expect(labElement(fixture).textContent).toContain('Touched: false');
    fixture.destroy();
  }));

  it('buffers title input until blur, cancels stale validation and handles explicit check failure/retry', fakeAsync(() => {
    const fixture = TestBed.createComponent(FormsSignalLabComponent);
    renderLab(fixture);
    const availability = fixture.debugElement.injector.get(LocalAvailabilityService);
    typeLab(fixture, '[data-title]', 'First', false);
    expect(availability.requests()).toEqual([]);
    expect(labElement(fixture).textContent).toContain('Buffered title: First');
    labInput(fixture, '[data-title]').dispatchEvent(new Event('blur')); renderLab(fixture);
    const oldId = availability.requests()[0]?.id ?? -1;
    expect(oldId).toBeGreaterThan(0);
    typeLab(fixture, '[data-title]', 'reserved');
    expect(availability.resolve(oldId)).toBeFalse();
    expect(availability.cancellations()).toBeGreaterThan(0);
    availability.resolve(availability.requests()[0]?.id ?? -1); renderLab(fixture);
    expect(labElement(fixture).textContent).toContain('This name is reserved');
    typeLab(fixture, '[data-title]', 'Allowed');
    availability.fail(availability.requests()[0]?.id ?? -1); renderLab(fixture);
    expect(labElement(fixture).textContent).toContain('Local availability failed');
    clickLab(fixture, 'Retry availability');
    const activeId = availability.requests()[0]?.id ?? -1;
    fixture.destroy();
    expect(availability.requests()).toEqual([]);
    expect(availability.resolve(activeId)).toBeFalse();
  }));

  it('bounds notes, resets arrays/record/buffered title and isolates component instances', fakeAsync(() => {
    const fixture = TestBed.createComponent(FormsSignalLabComponent);
    const other = TestBed.createComponent(FormsSignalLabComponent);
    renderLab(fixture); renderLab(other);
    clickLab(fixture, 'Add note'); clickLab(fixture, 'Add note'); clickLab(fixture, 'Add note');
    expect(labButton(fixture, 'Add note').disabled).toBeTrue();
    clickLab(fixture, 'Add note');
    expect(labElement(fixture).querySelectorAll('.note').length).toBe(3);
    clickLab(fixture, 'Remove note 2');
    expect(labButton(fixture, 'Add note').disabled).toBeFalse();
    clickLab(fixture, 'Toggle optional label');
    typeLab(fixture, '[data-title]', '<b>unsaved</b>', false);
    expect(labElement(fixture).querySelector('b')).toBeNull();
    expect(labInput(other, '[data-title]').value).toBe('');
    clickLab(fixture, 'Reset draft');
    expect(labElement(fixture).querySelectorAll('.note').length).toBe(0);
    expect(labInput(fixture, '[data-title]').value).toBe('');
    expect(fixture.componentInstance.canLeave()).toBeTrue();
    fixture.destroy(); other.destroy();
  }));

  it('binds native calendar strings and conditional acknowledgement, then resets the nested draft', fakeAsync(() => {
    const fixture = TestBed.createComponent(FormsSignalLabComponent);
    renderLab(fixture);
    clickLab(fixture, 'Fill sample');
    const availability = fixture.debugElement.injector.get(LocalAvailabilityService);
    availability.resolve(availability.requests()[0]?.id ?? -1); renderLab(fixture);
    const enabled = labInput(fixture, 'input[type=checkbox]');
    const start = labInput(fixture, 'input[aria-describedby=signal-start-error]');
    const end = labInput(fixture, 'input[aria-describedby=signal-end-error]');
    const ack = labInput(fixture, 'app-signal-ack-control input');
    expect(start.disabled).toBeTrue(); expect(ack.disabled).toBeTrue();
    enabled.click(); renderLab(fixture);
    expect(start.disabled).toBeFalse(); expect(ack.disabled).toBeFalse();
    typeLab(fixture, 'input[aria-describedby=signal-start-error]', '2026-10-02');
    typeLab(fixture, 'input[aria-describedby=signal-end-error]', '2026-10-01');
    ack.click(); renderLab(fixture);
    clickLab(fixture, 'Review errors');
    expect(end.getAttribute('aria-invalid')).toBe('true');
    expect(document.activeElement).toBe(end);
    expect(labButton(fixture, 'Save local draft').disabled).toBeTrue();
    enabled.click(); renderLab(fixture);
    expect(start.disabled).toBeTrue(); expect(start.value).toBe('2026-10-02');
    expect(ack.checked).toBeTrue();
    expect(labButton(fixture, 'Save local draft').disabled).toBeFalse();
    clickLab(fixture, 'Reset draft');
    expect(start.value).toBe(''); expect(end.value).toBe('');
    expect(ack.checked).toBeFalse(); expect(ack.disabled).toBeTrue();
    fixture.destroy();
  }));

  it('settles a manual save on forced destruction without publishing a late success', fakeAsync(() => {
    const fixture = TestBed.createComponent(FormsSignalLabComponent);
    renderLab(fixture);
    clickLab(fixture, 'Fill sample');
    const availability = fixture.debugElement.injector.get(LocalAvailabilityService);
    availability.resolve(availability.requests()[0]?.id ?? -1); renderLab(fixture);
    submitLab(fixture);
    fixture.destroy();
    expect(availability.requests()).toEqual([]);
  }));
});
